/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiacinco;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class Guiauno extends javax.swing.JFrame {

    /**
     * Creates new form Guiauno
     */
    public Guiauno() {
        initComponents();
        
    }
    
    Operaciones op = new Operaciones();
     ArrayList<Double> numeros = new ArrayList();
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox2 = new javax.swing.JComboBox<>();
        Progreso = new javax.swing.JProgressBar();
        jLabelVariable = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        RadioRadio = new javax.swing.JRadioButton();
        RadioDiametro = new javax.swing.JRadioButton();
        jButtonIngresar = new javax.swing.JButton();
        jButtonResultado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Área y diagonal 4 lados", "Circunferencia de un circulo", "Volumen de una esfera", "Volumen de un cubo", "Promedio de una muestra" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        getContentPane().add(Progreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        jLabelVariable.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVariable.setText("Ingresar:");
        getContentPane().add(jLabelVariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, -1));

        buttonGroup1.add(RadioRadio);
        RadioRadio.setForeground(new java.awt.Color(255, 255, 255));
        RadioRadio.setSelected(true);
        RadioRadio.setText("Radio");
        RadioRadio.setEnabled(false);
        RadioRadio.setOpaque(false);
        getContentPane().add(RadioRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        buttonGroup1.add(RadioDiametro);
        RadioDiametro.setForeground(new java.awt.Color(255, 255, 255));
        RadioDiametro.setText("Diametro");
        RadioDiametro.setEnabled(false);
        RadioDiametro.setOpaque(false);
        getContentPane().add(RadioDiametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.setEnabled(false);
        jButtonIngresar.setOpaque(false);
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jButtonResultado.setText("Resultado");
        jButtonResultado.setOpaque(false);
        jButtonResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GUÍA 1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bglogin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        if(jComboBox2.getSelectedIndex()==1 || jComboBox2.getSelectedIndex()==2){
            RadioRadio.setEnabled(true);
            RadioDiametro.setEnabled(true);
            jLabelVariable.setText("Ingresar radio/diametro:");
        } else {
            RadioRadio.setEnabled(false);
            RadioDiametro.setEnabled(false);
        }
        if (jComboBox2.getSelectedIndex()==0){
            jLabelVariable.setText("Ingresar lado:");
        } else if(jComboBox2.getSelectedIndex()==3){
            jLabelVariable.setText("Ingresar diagonal:");
            
        } 
        
        if (jComboBox2.getSelectedIndex()==4){
            jButtonIngresar.setEnabled(true);
            jLabelVariable.setText("Ingresar datos:");
        } else {
            jButtonIngresar.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButtonResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultadoActionPerformed
         ArrayList<Integer> calificaciones = new ArrayList();
        double input = Double.parseDouble(jTextField1.getText());
        if (jComboBox2.getSelectedIndex()==0){
            op.CalcularAreayDiagonal(input);
        } else if (jComboBox2.getSelectedIndex()==1){
            if (RadioRadio.isSelected()){
            op.CalcularCircunferenciaRadio(input);
            } else {
                op.CalcularCircunferenciaRadio(input/2);
            }
        } else if (jComboBox2.getSelectedIndex()==2){
            if (RadioRadio.isSelected()){
            op.CalcularVolumenEsfera(input);
            } else {
                op.CalcularVolumenEsfera(input/2);
            }
        } else if (jComboBox2.getSelectedIndex()==3){
            op.CalcularVolumenCubo(input);
        } else if (jComboBox2.getSelectedIndex()==4){
            double suma=0;
            for (int cont = 0 ; cont<numeros.size(); cont++){
                suma = suma + numeros.get(cont);
            }
            op.Promedio(suma);
            
        }
        op.mostrar();
    }//GEN-LAST:event_jButtonResultadoActionPerformed

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        if (numeros.size()<10){
            numeros.add(Double.parseDouble(jTextField1.getText()));
        System.out.println(numeros.size());
        Progreso.setValue(numeros.size()*10);
        } else {
            JOptionPane.showMessageDialog(null, "Ya ingresó todos los datos");
        }
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guiauno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guiauno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guiauno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guiauno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guiauno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Progreso;
    private javax.swing.JRadioButton RadioDiametro;
    private javax.swing.JRadioButton RadioRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonResultado;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelVariable;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
