/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiacinco;

import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class Guiatres extends javax.swing.JFrame {

    /**
     * Creates new form cpuframe
     */
    public Guiatres() {
        initComponents();
        
        
    }
    Smartphone telefono = new Smartphone();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCpu = new javax.swing.JTextField();
        txtPantalla = new javax.swing.JTextField();
        txtRam = new javax.swing.JTextField();
        txtGarantia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbMarca = new javax.swing.JComboBox<>();
        txtFrontal = new javax.swing.JTextField();
        txtTrasera = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBoxPrincipal = new javax.swing.JCheckBox();
        jCheckBoxSecundaria = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jCheckBoxFlash = new javax.swing.JCheckBox();
        txtBateria = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Puntaje de móviles");

        jLabel2.setText("CPU número de núcleos");

        jLabel3.setText("Tamaño de pantalla:");

        jLabel4.setText("Cantidad de RAM:");

        jLabel5.setText("Tiempo de garantía");

        jLabel6.setText("Precio:");

        jLabel7.setText("Marca:");

        txtCpu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCpuKeyTyped(evt);
            }
        });

        txtPantalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPantallaKeyTyped(evt);
            }
        });

        txtRam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRamKeyTyped(evt);
            }
        });

        txtGarantia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGarantiaKeyTyped(evt);
            }
        });

        jLabel8.setText("Cámaras:");

        cbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nexus", "Google", "Lenovo", "Huawei", "Sony", "Apple", "Samsung", "Alcatel", "LG", "Xiaomi" }));

        txtFrontal.setEditable(false);
        txtFrontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFrontalActionPerformed(evt);
            }
        });
        txtFrontal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFrontalKeyTyped(evt);
            }
        });

        txtTrasera.setEditable(false);
        txtTrasera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTraseraKeyTyped(evt);
            }
        });

        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBoxPrincipal.setText("Principal");
        jCheckBoxPrincipal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxPrincipalItemStateChanged(evt);
            }
        });

        jCheckBoxSecundaria.setText("Secundaria");
        jCheckBoxSecundaria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxSecundariaItemStateChanged(evt);
            }
        });

        jTextPane1.setEditable(false);
        jScrollPane2.setViewportView(jTextPane1);

        jCheckBoxFlash.setText("Flash");

        jLabel9.setText("Bateria:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCpu)
                                    .addComponent(txtPantalla)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 108, Short.MAX_VALUE))
                                    .addComponent(txtRam)
                                    .addComponent(txtGarantia)
                                    .addComponent(txtPrecio))
                                .addGap(16, 16, 16))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(100, 100, 100)
                                        .addComponent(txtBateria))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFrontal)
                                            .addComponent(jCheckBoxPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTrasera, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jCheckBoxSecundaria)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCheckBoxFlash)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBoxPrincipal)
                        .addComponent(jCheckBoxSecundaria)
                        .addComponent(jCheckBoxFlash)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFrontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrasera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpuKeyTyped
        char k = evt.getKeyChar();
        
        if (k<'0' || k>'9' || txtCpu.getText().length()==2){
            evt.consume();
        }
    }//GEN-LAST:event_txtCpuKeyTyped

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        if 
        (txtPantalla.getText().length()==0 || txtBateria.getText().length()==0
         || txtPrecio.getText().length()==0 || txtTrasera.getText().length()==0 || txtFrontal.getText().length()==0 || txtGarantia.getText().length()==0 || txtRam.getText().length()==0 ||txtRam.getText().length()==0) {
        JOptionPane.showMessageDialog(null, "Rellene todos los campos");
    } else {
              telefono.setPuntaje(0);
        double pantalla = Double.parseDouble(txtPantalla.getText());
        int bateria = Integer.parseInt(txtBateria.getText());
        int precio = Integer.parseInt(txtPrecio.getText());
        double principal = Integer.parseInt(txtTrasera.getText());
        double frontal = Integer.parseInt(txtFrontal.getText());
        int garantia = Integer.parseInt(txtGarantia.getText());
        int Cpu = Integer.parseInt(txtCpu.getText());
        int Ram = Integer.parseInt(txtRam.getText());
        telefono.BateriaPantalla(pantalla, bateria);
        telefono.refMarca(cbMarca.getSelectedIndex());
        telefono.rangoPrecio(precio);
        telefono.pixelaje(principal, frontal, jCheckBoxFlash.isSelected());
        telefono.garantia(garantia);
        telefono.Cpu(Cpu);
        telefono.Ram(Ram);
        
        jTextPane1.setText("El puntaje es:" + telefono.getPuntaje());
        }
        
      
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBoxPrincipalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxPrincipalItemStateChanged

        if(evt.getStateChange()==ItemEvent.SELECTED){
            txtFrontal.setEditable(true);
        } else {
            txtFrontal.setEditable(false);
        }
    }//GEN-LAST:event_jCheckBoxPrincipalItemStateChanged

    private void jCheckBoxSecundariaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxSecundariaItemStateChanged

        if(evt.getStateChange()==ItemEvent.SELECTED){
            txtTrasera.setEditable(true);
        } else {
            txtTrasera.setEditable(false);
        }
    }//GEN-LAST:event_jCheckBoxSecundariaItemStateChanged

    private void txtPantallaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPantallaKeyTyped
        char k = evt.getKeyChar();
        
        if (((k<'0' || k>'9') && k!='.') || (txtPantalla.getText().length()==3)){
            evt.consume();
        }
    }//GEN-LAST:event_txtPantallaKeyTyped

    private void txtRamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRamKeyTyped
        char k = evt.getKeyChar();
        
        if (((k<'0' || k>'9') && k!='.') || (txtRam.getText().length()==3)){
            evt.consume();
        }
    }//GEN-LAST:event_txtRamKeyTyped

    private void txtGarantiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGarantiaKeyTyped

        char k = evt.getKeyChar();
        
        if (k<'0' || k>'9' || (txtGarantia.getText().length()==2)){
            evt.consume();
        }
    }//GEN-LAST:event_txtGarantiaKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char k = evt.getKeyChar();
        
        if (((k<'0' || k>'9') && k!='.') || (txtPrecio.getText().length()==6)){
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtFrontalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFrontalKeyTyped
        char k = evt.getKeyChar();
        
        if (((k<'0' || k>'9') && k!='.') || (txtFrontal.getText().length()==4)){
            evt.consume();
        }
    }//GEN-LAST:event_txtFrontalKeyTyped

    private void txtTraseraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTraseraKeyTyped
        char k = evt.getKeyChar();
        
        if (((k<'0' || k>'9') && k!='.') || (txtTrasera.getText().length()==4)){
            evt.consume();
        }
    }//GEN-LAST:event_txtTraseraKeyTyped

    private void txtFrontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFrontalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFrontalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guiatres().setVisible(true);
                
                
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbMarca;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxFlash;
    private javax.swing.JCheckBox jCheckBoxPrincipal;
    private javax.swing.JCheckBox jCheckBoxSecundaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField txtBateria;
    private javax.swing.JTextField txtCpu;
    private javax.swing.JTextField txtFrontal;
    private javax.swing.JTextField txtGarantia;
    private javax.swing.JTextField txtPantalla;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRam;
    private javax.swing.JTextField txtTrasera;
    // End of variables declaration//GEN-END:variables
}
