/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiacinco;

import javax.swing.DefaultListModel;

/**
 *
 * @author Rodrigo
 */
public class Guiados extends javax.swing.JFrame {

    /**
     * Creates new form Guiados
     */
    public Guiados() {
        initComponents();
    }
    DefaultListModel listamodelo = new DefaultListModel();
    DefaultListModel lista = new DefaultListModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListAlfa = new javax.swing.JList<>();
        jButtonLetras = new javax.swing.JButton();
        jTxtLetras = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jListAlfa);

        jButtonLetras.setText("Ingresar datos");
        jButtonLetras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLetrasActionPerformed(evt);
            }
        });

        jTxtLetras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtLetrasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtLetrasKeyTyped(evt);
            }
        });

        jButton1.setText("Ordenar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese letras mayúsculas:");

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jTxtLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLetras)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(jTxtLetras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLetras)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtLetrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtLetrasKeyPressed
        
    }//GEN-LAST:event_jTxtLetrasKeyPressed

    private void jTxtLetrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtLetrasKeyTyped
        char c = evt.getKeyChar();
        int carac=(int)evt.getKeyChar();
        
        if (Character.isUpperCase(c) && Character.isLetter(c) && jTxtLetras.getText().length()==0) {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTxtLetrasKeyTyped

    private void jButtonLetrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLetrasActionPerformed
        listamodelo.addElement(jTxtLetras.getText());
        jListAlfa.setModel(listamodelo);
        jTxtLetras.setText("");

    }//GEN-LAST:event_jButtonLetrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String elemento1, elemento2;
        int ascii1, ascii2;
        char c1, c2;
        if (listamodelo.getSize()>=1){
            for(int ite=0 ; ite<listamodelo.getSize()-1 ; ite++){
                for (int ite2=0 ; ite2<listamodelo.getSize()-1 ; ite2++){
                    elemento1 = listamodelo.getElementAt(ite2).toString();
                    
                    
                    elemento2 = listamodelo.getElementAt(ite2+1).toString();
                    ascii1 = (int)elemento1.charAt(0);
                    ascii2 = (int)elemento2.charAt(0);;
                    
                    if (ascii1>ascii2){
                        listamodelo.setElementAt(elemento2, ite2);
                        listamodelo.setElementAt(elemento1, ite2+1);
                    }
                    
                }
            }
            jListAlfa.setModel(listamodelo);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        listamodelo.removeAllElements();
        jListAlfa.setModel(listamodelo);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guiados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guiados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guiados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guiados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guiados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonLetras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListAlfa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtLetras;
    // End of variables declaration//GEN-END:variables
}
