/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiacinco;

import javax.swing.DefaultListModel;

/**
 *
 * @author Rodrigo
 */
public class Guiados extends javax.swing.JFrame {

    /**
     * Creates new form Guiados
     */
    public Guiados() {
        initComponents();
    }
    DefaultListModel listamodelo = new DefaultListModel();
    DefaultListModel lista = new DefaultListModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListAlfa = new javax.swing.JList<>();
        jButtonLetras = new javax.swing.JButton();
        jTxtLetras = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jListAlfa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 220));

        jButtonLetras.setText("Ingresar datos");
        jButtonLetras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLetrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLetras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jTxtLetras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtLetrasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtLetrasKeyTyped(evt);
            }
        });
        getContentPane().add(jTxtLetras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtLetrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtLetrasKeyPressed
        
    }//GEN-LAST:event_jTxtLetrasKeyPressed

    private void jTxtLetrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtLetrasKeyTyped
        if (jTxtLetras.getText().length()==1) {
            evt.consume();
        }
    }//GEN-LAST:event_jTxtLetrasKeyTyped

    private void jButtonLetrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLetrasActionPerformed
        listamodelo.addElement(jTxtLetras.getText());
        jListAlfa.setModel(listamodelo);

    }//GEN-LAST:event_jButtonLetrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guiados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guiados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guiados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guiados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guiados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLetras;
    private javax.swing.JList<String> jListAlfa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtLetras;
    // End of variables declaration//GEN-END:variables
}
