/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiacinco;

/**
 *
 * @author Rodrigo
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButtonGuia3 = new javax.swing.JButton();
        jButtonGuia2 = new javax.swing.JButton();
        jButtonGuia1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jButton4.setText("Salir");
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jButtonGuia3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonGuia3.setText("APP GUIA 3 Y 4");
        jButtonGuia3.setOpaque(false);
        jButtonGuia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuia3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jButtonGuia2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonGuia2.setText("APP GUIA 2");
        jButtonGuia2.setOpaque(false);
        jButtonGuia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuia2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jButtonGuia1.setBackground(new java.awt.Color(204, 204, 204));
        jButtonGuia1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonGuia1.setText("APP GUIA 1");
        jButtonGuia1.setOpaque(false);
        jButtonGuia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuia1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bglogin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuia1ActionPerformed
        Guiauno ventana1 = new Guiauno();
        ventana1.setVisible(true);
        ventana1.setLocationRelativeTo(null);
       jButtonGuia1.setEnabled(false);
    }//GEN-LAST:event_jButtonGuia1ActionPerformed

    private void jButtonGuia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuia2ActionPerformed
        Guiados ventana2 = new Guiados();
        ventana2.setVisible(true);
        ventana2.setLocationRelativeTo(null);
       jButtonGuia2.setEnabled(false);
    }//GEN-LAST:event_jButtonGuia2ActionPerformed

    private void jButtonGuia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuia3ActionPerformed
        Guiatres ventana3 = new Guiatres();
        ventana3.setVisible(true);
        ventana3.setLocationRelativeTo(null);
       jButtonGuia3.setEnabled(false);
    }//GEN-LAST:event_jButtonGuia3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonGuia1;
    private javax.swing.JButton jButtonGuia2;
    private javax.swing.JButton jButtonGuia3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
